### ISSUE TITLE
Add short-hand to set main color

### ISSUE THREAD

**Issue by egoist** [egoist/docute#60]
the color for progress bar and links, titles etc is `#4078c0`, an option `mainColor: '#xxxxxx'` might be handy.

**Comment by jrappen** [comment]
Something like:

```css
html {
  --redish: #e63525;
}

a {
  color: var(--redish);
}
```

might help.
